version: '2'

volumes:
  gems:
    driver: local

services:
  test: &base
    image: ruby:2.3.1
    entrypoint: /usr/src/app/test-entrypoint.sh  
    command: bundle exec guard start --no-bundler-warning --no-interactions
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - gems:/usr/local/bundle
    stdin_open: true
    tty: true

  app:
    <<: *base
    entrypoint: /usr/src/app/development-entrypoint.sh  
    command: bash
    env_file:
      - dev.env
